### ISSUE TITLE
Fail to launch docker image after rebuilding image

### ISSUE THREAD

**Issue by kevmando** [cloudfoundry/nginx-cnb#2]
What version of Cloud Foundry and CF CLI are you using? 
```
cf 2.141.0
cf-cli 6.44.1+c3b20bfbe.2019-05-08
pack v0.5.0
```

What version of the buildpack you are using?
`latest I assume`

If you were attempting to accomplish a task, what was it you were attempting to do?
```
I'm trying to build a docker image by **pack build** and debug some issues and build again and test.

So steps are;
1. pack build pack --path /where/is/app/
2. docker run --rm -p 8080:8080 -e PORT=8080 pack:latest
3. pack build pack --path /where/is/app/
4. docker run --rm -p 8080:8080 -e PORT=8080 pack:latest
```

What did you expect to happen?
`Rebuilt docker image would be launched fine.`

What was the actual behavior?
```
New docker image doesn't launch with the following error.
Once I remove all previous layers and build again, then it works.
Even there is no change in files.

$docker run --rm -p 8080:8080 -e PORT=8080 pack:latest
ERROR: failed to launch: determine start command: process type web was not found

```
Can you provide a sample app?
https://github.com/cloudfoundry/nginx-cnb/tree/master/integration/testdata/simple_app

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by dfreilich** [comment]
Hey @kevmando , thanks for filing the bug report here! I reproduced it, and we'll fix it as soon as priorities allow.

**Comment by kvedurmu** [comment]
Thanks again for reporting this @kevmando. This was recently fixed in master as a part of https://github.com/cloudfoundry/nginx-cnb/commit/75e72fcd81266d7e82fc26bf105667464c283fb2
